### ISSUE TITLE
PyonObject.dump unintended behavior when file_object is passed.

### ISSUE THREAD

**Issue by dapryor** [lagmoellertim/pyon#5]
From the docstring:

> :param file_object: Specify a file the JSON object get written to, **only returns the data when not specified**

Data will be returned with or without a file_object being passed. due to the return at the end of the function.

```
with open("test.txt", 'w') as f:
    print(p.dump(file_object=f))
    
{'test': {123: {}}}
```

**Comment by lagmoellertim** [comment]
Hey,
My Implementation needs the file object directly like this:
`p.dump(file_object=open("test.txt", 'w'))`

Since `open("test.txt", 'w')` is the file object and `with ... as f:` is only a wrapper, I think that my current implementation is pretty understandable. If you think otherwise, feel free to suggest a different wording or implementation.

**Comment by dapryor** [comment]
I am referring to the last part of the param description.  It reads as if the function should not return the dumped data if a file_handler is passed.

Calling the function like
```
print(p.dump(file_object=open("test.txt", 'w'))) 
```

returns the dumped date:
```
{'test': {123: {}}}
```

**Comment by lagmoellertim** [comment]
I implemented the file save as an “add on” to the return argument since I think it could be useful to save the output to a file and get it returned, since return none wouldn’t add any particular benefit

**Comment by dapryor** [comment]
I could update the description to better match that behavior?

**Comment by lagmoellertim** [comment]
Sure, that would be great:+1:

**Comment by dapryor** [comment]
New description merged. Closing issue.
